### ISSUE TITLE
Real Time Data consumption even in background...

### ISSUE THREAD

**Issue by sirvon** [Syncano/syncano-android#6]
Jus wondering before I dive in on my own recipe....

Have you guys been cooking up ways to still get the data even when the activity/app is in the background....

It seems now when we come back to an activity that is receiving real time channel data, that we have to make calls to syncano and check what we missed since the last data we received.

as opposed to the app always receiving the data, storing it in the background and displaying it upon return.

thanks for the lib...

**Comment by MariuszWisniewski** [comment]
So far unfortunately not. The way we and other people have been doing it so far, is to:
1) ask for new data on start (GET on /class/xx/objects/ endpoint) and after that use Channels for real-time sync

We are aware this is not the perfect way to do it, and we're improving it now and working on catch up with the iOS library, which is our testing field - we add and test new features there and then move it elsewhere when we're satisfied.

Since it's not implemented yet - is there a way you'd like to work with our library that would provide data you missed? I will also get back to you when we have a draft of how we'd like to implement it and if needed @stasheq will be able to answer more detailed Android questions.
